name: Docs Quality
on:
    push:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Codespell (spelling)
              uses: codespell-project/actions-codespell@v2
              with:
                  path: "."
                  ignore_words_list: "StudyTrack"
